// <auto-generated />

namespace School.Database.Migrations
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;

    [DbContext(typeof(SchoolContext))]
    internal class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.UseIdentityByDefaultColumns().HasAnnotation("Relational:MaxIdentifierLength", 63).
                         HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity(
                "School.Database.Cabinete",
                b =>
                {
                    b.Property<string>("Id").HasColumnType("text");

                    b.Property<string>("Name").HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cabinetes");
                });

            modelBuilder.Entity(
                "School.Database.Class",
                b =>
                {
                    b.Property<string>("Id").HasColumnType("text");

                    b.Property<int>("Grade").HasColumnType("integer");

                    b.Property<char>("Litera").HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity(
                "School.Database.Subject",
                b =>
                {
                    b.Property<string>("Id").HasColumnType("text");

                    b.Property<int>("MaxPerWeek").HasColumnType("integer");

                    b.Property<string>("Name").HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubjectsPget");
                });

            modelBuilder.Entity(
                "School.Database.Teacher",
                b =>
                {
                    b.Property<string>("Id").HasColumnType("text");

                    b.Property<string>("Name").HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}